services:
  mongodb:
    image: mongo:latest
    container_name: gigtrack_mongodb
    restart: always
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_DATABASE: gigtrackDB
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express:1.0.2
    container_name: gigtrack_mongo_express
    restart: always
    ports:
      - "8082:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH: "false"
    depends_on:
      - mongodb

volumes:
  mongodb_data: